### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by lavinal712** [XGGNet/StegaNeRF#1]
When I input command:
`bash stega_llff.sh fern cvpr_logo.png 0`
![微信图片_20230330145739](https://user-images.githubusercontent.com/98888959/228760832-386ee3e4-a202-48e2-88b1-5295439e0131.jpg)
Specifically, the command in stega_llff.sh goes wrong:
`python opt.py -t ckpt_svox2_low  ../data/llff/fern --gpuid 0 -c configs/llff_low.json`
I want to know why this problem happens, and how to deal with it.

**Comment by AryaStar** [comment]
I meat the same problem, I would appreciate it if you can tell me how to deal with it.

**Comment by AryaStar** [comment]
Now, I have solved this problem with the help of https://github.com/sxyu/svox2/issues/49. We need to use cmake to compile the svox2 file before running this project.

**Comment by lavinal712** [comment]
https://blog.csdn.net/weixin_40678496/article/details/124348438

This blog may be helpful. Now both Plenoxels and StegaNeRF projects can run on my PC, partly. Because I've only got 8GB for the CUDA. :)

Anyway, thanks for discussing with me and wish that you will get some "magic" in your researching path, so as deep learning.

**Comment by JosTheBossX** [comment]
Hello, Did anyone find any solution to this problem? Even I am facing this problem.

**Comment by chenxinli001** [comment]
Please refer to https://github.com/sxyu/svox2/issues/49. You need to use cmake to compile the svox2 file before running this project. Thanks!

> Hello, Did anyone find any solution to this problem? Even I am facing this problem.
